# development docker-compose file
version: '2.1'

services:

  scraper:
    image: public.ecr.aws/unocha/hdx-scraper-worldbank:0.1
    volumes:
      - "./:/srv"
    working_dir: /srv
    command: sh ./run-dev.sh
    env_file:
      - run_env
