class OtherData:
    sources = [
        {
            "id": "2",
            "lastupdated": "2019-09-27",
            "name": "World Development Indicators",
            "code": "WDI",
            "description": "",
            "url": "",
            "dataavailability": "Y",
            "metadataavailability": "Y",
            "concepts": "3",
        },
        {
            "id": "57",
            "lastupdated": "2019-05-01",
            "name": "WDI Database Archives",
            "code": "WDA",
            "description": "",
            "url": "",
            "dataavailability": "Y",
            "metadataavailability": "Y",
            "concepts": "4",
        },
        {
            "id": "62",
            "lastupdated": "2017-05-09",
            "name": "International Comparison Program (ICP) 2011",
            "code": "ICP",
            "description": "",
            "url": "",
            "dataavailability": "N",
            "metadataavailability": "Y",
            "concepts": "4",
        },
    ]
