license_id: "cc-by"
notes: "Data used to update country toplines in HDX. Contains data from World Bank's [data portal](http://data.worldbank.org/)."
caveats: ""
methodology: "Registry"
dataset_source: "World Bank"
package_creator: "mcarans"
private: False  # has to be True or False
