license_id: "cc-by-igo"
caveats: "The indicators' sources are mentioned in the resource descriptions."
methodology: "Registry"
dataset_source: "World Bank"
package_creator: "mcarans"
private: False  # has to be True or False
