# Collector specific configuration
base_url: "http://api.worldbank.org/"
indicator_list:
  - "SP.POP.TOTL"
  - "SP.POP.DPND.OL"
  - "SP.POP.DPND.YG"
  - "SH.DTH.IMRT"
  - "SM.POP.TOTL.ZS"
  - "AG.LND.TOTL.K2"
  - "SP.POP.GROW"
  - "EN.POP.DNST"
  - "EN.URB.MCTY"
  - "NY.GNP.MKTP.CD"
  - "SI.POV.DDAY"
  - "SP.DYN.AMRT.FE"
  - "SP.DYN.AMRT.MA"
  - "LP.LPI.OVRL.XQ"
  - "IS.RRS.TOTL.KM"
  - "NY.GNP.MKTP.PP.CD"
  - "NY.GDP.PCAP.PP.CD"
  - "NY.GNP.PCAP.PP.CD"
  - "DT.ODA.ODAT.PC.ZS"
  - "IT.CEL.SETS.P2"
  - "NE.CON.PRVT.PP.KD"
  - "EG.ELC.ACCS.ZS"
  - "SI.POV.GINI"
  - "FP.CPI.TOTL.ZG"
  - "SN.ITK.DEFC.ZS"
  - "IT.MLT.MAIN.P2"
  - "NY.GDP.PCAP.PP.KD"
  - "SH.DYN.AIDS.ZS"
  - "SL.EMP.INSV.FE.ZS"
topline_indicators:
  - "SP.POP.TOTL"
  - "EN.POP.DNST"
  - "NY.GDP.PCAP.PP.CD"
  - "AG.LND.TOTL.K2"
