# Collector specific configuration
base_url: "http://api.worldbank.org/"
indicator_limit: 60
character_limit: 1500
indicator_subtract: 5
tag_mappings:
  financial sector: "economics"
  social protection: "socioeconomics"
  private sector: "economics"
  public sector: "economics"
  science: "economics"
  millenium development goals: "millennium development goals - mdg"
  external debt: "economics"
topline_indicators:
  - "SP.POP.TOTL"
  - "EN.POP.DNST"
  - "NY.GDP.PCAP.PP.CD"
  - "AG.LND.TOTL.K2"
