# Collector specific configuration
base_url: "https://api.worldbank.org/"
indicator_limit: 40
character_limit: 1000
tag_mappings:
  financial sector: "economics"
  social protection: "socioeconomics"
  private sector: "economics"
  public sector: "economics"
  science: "economics"
  millenium development goals: "millennium development goals - mdg"
  external debt: "economics"
combined_qc_indicators:
  - code: "SP.POP.TOTL"
    title: "Total Population"
    unit: "People"
  - code: "SP.DYN.LE00.IN"
    title: "Life Expectancy at Birth"
    unit: "Years"
  - code: "SE.PRM.ENRR"
    title: "Primary School Enrollment"
    unit: "Gross Percentage"
topline_indicators:
  - "SP.POP.TOTL"
  - "EN.POP.DNST"
  - "NY.GDP.PCAP.PP.CD"
  - "AG.LND.TOTL.K2"
